server:
  port: 8001

jwt:
  secret: a0b0732efc4eea28a692b00dc4cd481ca0b0732efc4eea28a692b00dc4cd

global:
  filter:
    exclude-path:
      - POST:/api/auth/login
      - POST:/api/user/signup
      - POST:/api/auth/encode
      - POST:/api/auth/email
      - POST:/api/auth/email/verify

spring:
  application:
    name: gateway

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8004/eureka
  instance:
    prefer-ip-address: true